#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure textproc/expat
  pkg ensure textproc/py27-expat textproc/py-expat

  block compile virtualenv
  ln -nfs "$shome/vendor/virtualenv/bin/vca" "$shome/bin/"
}

bootstrap
